### ISSUE TITLE
1.7 version?

### ISSUE THREAD

**Issue by Techokami** [PC-Logix/OpenPrinter#1]
Hi, I was directed here by the creator of OpenComputers, since OC was missing printers, and this mod implements what I was missing! Except this was made for the 1.6.x branch of Minecraft.
Any plans to update to 1.7.2?

**Comment by CaitlynMainer** [comment]
Well currently it implements a model, and a broken GUI :P Once I get the mod working in 1.6 I may try to get a 1.7 version working.

**Comment by Techokami** [comment]
Awesome, thanks for letting me know. Can't wait to see this mod finished :)

**Comment by CaitlynMainer** [comment]
Heh.. seems I forgot to update this when I released the 1.7 build... it's here! http://lanteacraft.com/jenkins/job/OpenPrinter1.7/

**Comment by Techokami** [comment]
As I said on IRC, thank you!
