### ISSUE TITLE
OpenComputers 1.4 support?

### ISSUE THREAD

**Issue by LizzyTrickster** [PC-Logix/OpenPrinter#13]
Would be nice to see it for 1.4 OC, OpenPrinter is currently the only mod holding me back from using OC 1.4 on my server

**Comment by CaitlynMainer** [comment]
It does now. http://pc-logix.com/mods/   "The latest release of OpenPrinter for 1.7 is OpenPrinter-MC1.7.10-OC1.4-0.1.0.80.jar. Built: October 18 2014 08:01:11 PM."

**Comment by Techokami** [comment]
If you hadn't done this, I would have made a PR for it.
