### ISSUE TITLE
Incorrect number for argument

### ISSUE THREAD

**Issue by marcin212** [PC-Logix/OpenPrinter#27]
Look at [#L124](https://github.com/PC-Logix/OpenPrinter/blob/1.7/src/main/java/pcl/openprinter/tileentity/PrinterTE.java#L124). I think there should be `args.checkInteger(0)`

**Comment by CaitlynMainer** [comment]
That's not what I have locally, and that file has not changed in _ages_ So color me confused.  Umm, "fixed" locally?
