### ISSUE TITLE
Feature Request: (Dyeable?) Folders!

### ISSUE THREAD

**Issue by MyNameIsKodos** [PC-Logix/OpenPrinter#29]
9-slot inventories, able to hold papers and possibly packets? (Explained below).

A packet would be anywhere from 2-4 papers crafted with paperclips (No idea how to make these) and would be usable like a signed book, where you can open it, read it, and flip through the pages.

If folders were dyable, this would allow the player to have a rudimentary sorting system for their papers, and would be neat for some of the more RP-oriented servers since things like ExU filing cabinets exist.

**Comment by CaitlynMainer** [comment]
Implemented in latest build
