### ISSUE TITLE
Block Textures

### ISSUE THREAD

**Issue by Timmy94W** [PC-Logix/OpenPrinter#3]
I have you the Black instant the 3D Model.
Then i See this: http://www7.pic-upload.de/02.05.14/6fxof2g4hbu9.png

**Comment by CaitlynMainer** [comment]
This is currently the texture for the block. No one had a decent printer block texture, so I used the UVWrapped texture from the model.

**Comment by Timmy94W** [comment]
https://googledrive.com/host/0B9Y6n3Mzv6PHbEZBcHQ5VFo2N3c/index.html
 I have made some Textures.

**Comment by CaitlynMainer** [comment]
Implemented in latest build
