### ISSUE TITLE
writeln() - Can't center and set color?

### ISSUE THREAD

**Issue by mzx987** [PC-Logix/OpenPrinter#30]
Not sure if it's just me, but I can't seem to set the color AND center text at the same time with this function.

**Comment by MyNameIsKodos** [comment]
A page is around 24-26 letters in width, give or take depending on the width of characters you use. To center, you can easily just check the length of your string and do some math.

As for setting colors, standard MC formatting is support, so just use the section sign to assign colors to text.

**Comment by mzx987** [comment]
I feel it would be more convenient if I had the ability to center and color. But I guess that would work just as well. Thanks for the suggestion.

**Comment by CaitlynMainer** [comment]
Is this still an issue? I'm pretty sure writeln takes string, int, string so writeln("message", 0xFF00FF,"center") should center align a string and color it.
