### ISSUE TITLE
1.10.2: Broken Models

### ISSUE THREAD

**Issue by zack-emmert** [PC-Logix/OpenPrinter#38]
Both the printer and shredder show both in inventory and placed in the world as blocks, with no custom model. The filing cabinet shows a missing texture in my inventory, and a block when placed in the world

**Comment by zack-emmert** [comment]
Here is the minecraft log file: http://paste.ee/p/9IOpZ

**Comment by CaitlynMainer** [comment]
There are no custom models in 1.8+   In 1.9.4 everything works fine, this must be some subtle change in 1.10, I'll look into it.

**Comment by CaitlynMainer** [comment]
Could you see if the latest build on curse fixes your issue?
