### ISSUE TITLE
[Question] Status of 1.11.2 port

### ISSUE THREAD

**Issue by brisingraerowing** [PC-Logix/OpenPrinter#39]
Just curious about the status of porting to 1.11.2. Not asking for a date or anything, just wondering.

Also, this is a very cool mod.

**Comment by CaitlynMainer** [comment]
It's non existent currently.

**Comment by brisingraerowing** [comment]
I actually was able to port it to 1.11.2 myself, and it builds, but I get an error stating it can't find Forge: Any when trying to run it. 😕 Not sure why that is, as Forge has to be there for it to run in the first place! 😖 

Also, I can do a pull request if you want. I created a new branch called 1.11.2 for the port.

**Comment by CaitlynMainer** [comment]
Or, just commit the code to your fork so I can take a look at it... I'm planning a pretty much total rewrite for 1.11+ but seeing your code would be helpful.

**Comment by brisingraerowing** [comment]
Will do.

**Comment by brisingraerowing** [comment]
Done.

**Comment by CaitlynMainer** [comment]
Awesome, thanks I got super busy this weekend :/  I'll work on this ASAP though.

**Comment by brisingraerowing** [comment]
I was rather busy this weekend as well (mostly doing things for my mother, as she has been sick recently).

**Comment by brisingraerowing** [comment]
I just figured out the "Forge: Any" issue: mcmod.info was incorrect for 1.11.2. 🤦‍♂️

**Comment by oliverrook** [comment]
Before you release a 1.11 can you please fix the issue I found above this one?

**Comment by CaitlynMainer** [comment]
@oliverrook that issue has been fixed in 1.9.4/1.10.2 as well as the 1.11.2 port.

**Comment by CaitlynMainer** [comment]
@BrisingrAerowing Thank you for porting to 1.11, I don't have the time for a rewrite like I had hoped.. so I took your fork made some quick changes and pulled it locally.  I'll work on 1.12 as soon as I'm done with a largish electronics project I'm working on with a friend.  Thank you again!

**Comment by brisingraerowing** [comment]
There's a few things I had missed in there:

- All references to null for ItemStacks should be changed to ItemStack.EMPTY
- Inventories should use NonNullList instead of an array (Use NonNullList.from to create it with a size and initial values)

Null item stacks will crash MC, so those need to be changed.

I can make these fixes and do a pull request if you want. I can also do some initial work on 1.12.1.

I'm on my iPad right now, so I may have missed a few things.

**Comment by CaitlynMainer** [comment]
Sure, that would be great, thanks

**Comment by brisingraerowing** [comment]
I'll do that then. It might be a bit, as I need to help my mom with cleaning (she has several physical issues and can't do very much at once).

**Comment by CaitlynMainer** [comment]
I did a few null -> ItemStack.EMPTY a bit ago, not sure what else needs done.

**Comment by brisingraerowing** [comment]
I just did a push to my fork with some changes.  Models and textures don't work at all right now (in a Dev Env at least. I haven't tried an actual build yet), and I have no idea what is wrong there. I also couldn't get the blocks (Printer, Shredder, File Cabinet) to show up in the creative inventory. I tried registering ItemBlocks for each one, but that crashed the game with no output when I went to debug it.

**Comment by CaitlynMainer** [comment]
Alright, I've fixed the models and textures, and all of the blocks are now registered.  Rotation on the blocks is still broken, and opening the inventory for them will crash the game still.

**Comment by ben-mkiv** [comment]
closing this...

replaced IInventory by ItemHandler + Capability and moved recipes to JSON files (so everything should be up2date now)

old printer Model is also back

latest 1.12.2 build is on curseForge now
https://www.curseforge.com/minecraft/mc-mods/openprinter/files
