### ISSUE TITLE
Xerox script fix request

### ISSUE THREAD

**Issue by IKnowBashFu** [PC-Logix/OpenPrinter#41]
The xerox script on 1.10.2 seems to be slightly off. I'd make a PR, but I can't seem to find your 1.10.2 branch, and I'm also not sure if this reaches to other branches.

The xerox script has `printer.setTitle(pageTitle)` on line 30, but in order for every page printed to have the proper title, that line needs to be in the for loop that starts on line 31.

**Comment by CaitlynMainer** [comment]
There is no 1.10 branch, 1.10 support is in the 1.9.4 branch.
