### ISSUE TITLE
[1.12 issue] The text on papers in folders is misaligned

### ISSUE THREAD

**Issue by ZefTheFox** [PC-Logix/OpenPrinter#46]
Minecraft version 1.12.2
OpenPrinter version 0.1.0.2.2

Whenever a paper is put into a folder its text is misaligned from the paper making it difficult to read
![image](https://user-images.githubusercontent.com/44857466/54637605-60ecf000-4a5f-11e9-9889-a91caf6b55f4.png)

A sheet alone works perfectly fine
![image](https://user-images.githubusercontent.com/44857466/54637555-4581e500-4a5f-11e9-8ec6-9df323de78e2.png)

**Comment by ben-mkiv** [comment]
fixed in the current build
https://www.curseforge.com/minecraft/mc-mods/openprinter/files
