### ISSUE TITLE
[1.7.2] Crafting recipe collision with Tinker's Construct

### ISSUE THREAD

**Issue by Techokami** [PC-Logix/OpenPrinter#5]
Yep, another issue with OpenPrinter and TCon. The Printer Paper Roll item can't be crafted, as TCon trumps the recipe for the Paper Stack item (which uses 4x1 paper, instead of 4x64...).
Maybe this can be fixed with an option/a check for TCon, and if it's present, add a recipe that turns 4x16 paper stacks into a Printer Paper Roll?

Thank you very much for this mod :)

P.S. Are you also keeping changes up-to-date with both branches? I just grabbed the latest 1.7.2 build of OpenPrinter from Jenkins, and it still has the crafting issue from #4

**Comment by CaitlynMainer** [comment]
Closed in build 30
