### ISSUE TITLE
[Bug report] folder crash

### ISSUE THREAD

**Issue by AR2000AR** [PC-Logix/OpenPrinter#50]
Crashed when trying to open the folder with only the creative printed page inside. Could be an issue with optifine.
**Step to reproduce**
- Take a folder and a printed page from the crative tab
- Put the page in the folder
- Open the folder

**Crash report :**
[crash-2019-10-25_14.09.03-client.txt](https://github.com/PC-Logix/OpenPrinter/files/3773964/crash-2019-10-25_14.09.03-client.txt)

**Comment by ben-mkiv** [comment]
thanks for reporting the issue, its fixed in dev.

I'll leave this bug opened until a official release is available on curseForge, you can download a fixed build here:
http://ci.pc-logix.com/job/OpenPrinter-1.12/8/artifact/build/libs/OpenPrinter-1.12.2-0.1.0.8.jar

**Comment by AR2000AR** [comment]
I will download it later. Thx for the quick answer.

**Comment by ben-mkiv** [comment]
official release (1.12.2-0.1.0.9) is now on curseForge
