### ISSUE TITLE
[Feature request] Simpler printer model

### ISSUE THREAD

**Issue by AR2000AR** [PC-Logix/OpenPrinter#51]
The printer model is really nice but doesn't fit well in Minecraft. Could you add a way to choose between the current model and a cube one ?

**Comment by ben-mkiv** [comment]
thats the closest you can get at the moment (but it will still have the non cubic hitbox of the 3D model)

https://github.com/PC-Logix/OpenPrinter/blob/1.12.1/resourcepacks/openprinter_old_printer_model_resourcepack.zip

https://minecraft.gamepedia.com/Tutorials/Loading_a_resource_pack

![](https://i.imgur.com/MyCzTAD.png)

**Comment by AR2000AR** [comment]
thx
