### ISSUE TITLE
Text Goes FLYING of the page

### ISSUE THREAD

**Issue by Kerbal-Man** [PC-Logix/OpenPrinter#54]
![image](https://user-images.githubusercontent.com/100152985/161647700-3fc8976a-d33b-4b4a-9f04-723ed8b4085f.png)
Um What?

Even worse when full screening 
![image](https://user-images.githubusercontent.com/100152985/161647800-fd6ab4b3-21d2-4935-8dbc-28abd3252758.png)

**Comment by Kerbal-Man** [comment]
I used op.writeln("String",0xIForgotWhatIputHere"center")

**Comment by CaitlynMainer** [comment]
MC Version?
Forge Version?
Mod version?

**Comment by Kerbal-Man** [comment]
1.12.2
14.23.5.2860
![image](https://user-images.githubusercontent.com/100152985/161649567-3d08def9-3955-4c6c-8c4d-40e3b0955191.png)

**Comment by Kerbal-Man** [comment]
Bruh

**Comment by CaitlynMainer** [comment]
Don't leave spam responses...

**Comment by Kerbal-Man** [comment]
What does that even mean?

**Comment by CaitlynMainer** [comment]
Fixed here: https://www.curseforge.com/minecraft/mc-mods/openprinter/files/3735744 As soon as CurseForge approves the build
