### ISSUE TITLE
it wont print

### ISSUE THREAD

**Issue by LittleTimmy52** [PC-Logix/OpenPrinter#55]
im new to open computers and open printers, i did what i could, but it just wont print, how could i print just some simple text or something this is what i got
![Capturemc](https://user-images.githubusercontent.com/90333044/193296107-a9db8295-890c-42ab-9c1e-a41b2ac9c0e9.JPG)

**Comment by LittleTimmy52** [comment]
i forgot to mention yes it has paper and ink and is connected to computer

**Comment by CaitlynMainer** [comment]
What version of Minecraft and mod?

**Comment by LittleTimmy52** [comment]
it is mc v 1.10.2 open printer 0.1.0.7.7

**Comment by LittleTimmy52** [comment]
wait a minuit, does the printer also need power, i only have it connected to the computer

**Comment by LittleTimmy52** [comment]
i will try that once i get more resources

**Comment by LittleTimmy52** [comment]
still broken it didnt print

**Comment by CaitlynMainer** [comment]
No, it doesn't need power. Also please don't spam comments, there is an edit button under the 3 dots to the right of the comment, you can edit your previous comment to add more information.  I am investigating the issue.

**Comment by LittleTimmy52** [comment]
oh sorry about that, and thanks

**Comment by CaitlynMainer** [comment]
![image](https://user-images.githubusercontent.com/1423429/193328359-2994ed2a-864e-4526-9e35-2ce211531960.png)
This works fine for me with OpenComputers-MC1.10.2-1.7.5.245, OpenPrinter-1.9.4-0.1.0.7, and Minecraft 1.10.2 Forge 12.18.3.2511

Using the same code you posted above:
![image](https://user-images.githubusercontent.com/1423429/193328654-484a6518-3f30-43d8-8429-a6d3a6440eda.png)

Please confirm you have Black *AND* Color ink in the printer, just like the real thing it won't print if it's missing one.

**Comment by CaitlynMainer** [comment]
Please confirm you have Black *AND* Color ink in the printer, just like the real thing it won't print if it's missing one.

**Comment by LittleTimmy52** [comment]
wait i needed color to
ok makes sense
ill do that when i go back on that world
thanks for your help

**Comment by CaitlynMainer** [comment]
![image](https://user-images.githubusercontent.com/1423429/193329411-a28ede51-d268-4e97-8abc-145b031bafe3.png)
![image](https://user-images.githubusercontent.com/1423429/193329601-b53f859e-e56b-4f25-8e40-0ef80fdc4e5e.png)
