### ISSUE TITLE
[1.7.2] Printer UI duplicating items?!

### ISSUE THREAD

**Issue by Techokami** [PC-Logix/OpenPrinter#6]
So I NEI'd myself a printer, both types of ink cartridges, and a roll of paper. I went to put everything into the printer and... my inventory kept getting jumbled? And it duplicated the ink and paper?!
This testing was done in multiplayer.

**Comment by jaquadro** [comment]
I have proposed a fix for this on PR #8

**Comment by CaitlynMainer** [comment]
Merged the 2 that will merge cleanly, Trying to get a non stupid Git client to work. GitHub's client locks loading the changeset.  Thanks for the PRs @jaquadro!

**Comment by jaquadro** [comment]
I recommend SourceTree as a free and high quality git client (Windows and Mac, even).  Paired with DiffMerge for merging.

**Comment by Techokami** [comment]
Man that sounds easier than what I had to do for my copy (hand merging! Augh)

**Comment by CaitlynMainer** [comment]
Fix't!
